spring:
  application:
    name: huali-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.23:8848 # Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.2.23:8858 # sentinel dashboard 地址
        port: 8719 # 默认为8719，如果被占用会自动+1，直到找到为止
      datasource: # 流控规则持久化到nacos
        dsl:
          nacos:
            server-addr: 192.168.2.23:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"
