huali:
  shiro:
    authc-enable: true
    login-url: /unauthorized
    unauthorized-url: /forbidden
    cookie-name: HUALI-JSESSIONID
    filter-chain-definitions: /unauthorized,/forbidden,/swagger**,/swagger**/**,/*/api-docs
    redis:
      session-enable: false
      replica-enable: false
      master-host:
      master-port:
      master-password:
      slaves:
